# Generated by Django 4.2.10 on 2024-12-07 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0011_attendance_hod'),
    ]

    operations = [
        migrations.AddField(
            model_name='hod',
            name='profile_pic',
            field=models.ImageField(blank=True, help_text='Upload a profile picture', null=True, upload_to='hod_profile_pics/'),
        ),
        migrations.AddField(
            model_name='staff',
            name='profile_pic',
            field=models.ImageField(blank=True, help_text='Upload a profile picture', null=True, upload_to='staff_profile_pics/'),
        ),
    ]
